# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on: [push]

jobs:
  build:
    strategy:
        matrix:
          java_version: [17, 21, 23]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5.0.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3.5.0
      - name: Build with Gradle & JDK ${{ matrix.java_version }}
        uses: gradle/actions/setup-gradle@v3.5.0
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: takanori-ugai/D2J
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5.6.2
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
